# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
        env:
          GITHUB_TOKEN: "${{ secrets.GTOKEN }}"
          GITHUB_TOKEN1: "${{ secrets.GTOKEN }}"

      - name: Clone Code
        shell: bash
        continue-on-error: true
        run: |
          git clone https://oauth2:${{ secrets.GTOKEN }}@github.com/parserpp/icpRes.git  ../icp

      - name: Install dependencies
        shell: bash
        continue-on-error: true
        run: |
          cd ../icp
          echo "查看文件树"
          tree
          echo "开始安装依赖"
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Code for test
        shell: bash
        continue-on-error: true
        run: |
          cd../icp
          python main.py
